import org.apache.shiro.SecurityUtils
import org.codehaus.groovy.grails.commons.GrailsClass

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class ShiroSecurityFilters {
    def filters = {
        all(uri: "/**") {
            before = {
                // Ignore direct views (e.g. the default main index page).
                if (!controllerName) return true
                //this is handled by shiro's filter map
                if (request.requestURL.contains("/rest/")) return true

                def roles = getRoleMap(controllerName)
                if (roles) {
                    accessControl(auth: false) {
                        def hasAccess = true
                        roles.each {
                            String action = it.key
                            if(action.trim() != "*") {
                                log.warn "converting action [$action] to * since action level security is not permitted"
                            }
                            log.debug "checking for access to $controllerName for role ${it.value}"
                            hasAccess = hasAccess && role(it.value)
                        }

                        return hasAccess
                    }
                }
                GrailsClass controllerClass = grailsApplication.getArtefactByLogicalPropertyName("Controller", controllerName)

                def isProtected = controllerClass.getPropertyValue("isProtected", Boolean)
                if (isProtected) {
                    def notLoggedIn = SecurityUtils.subject.principal == null
                    if (notLoggedIn) {
                        //will force a login
                        accessControl()
                    }
                }
            }
        }
    }
}
